In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

In [4]:
x = data [['size','year']]
y= data['price']

In [5]:
reg = LinearRegression()

In [6]:
reg.fit(x,y)

LinearRegression()

In [7]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [8]:
reg.intercept_

-5772267.017463282

In [9]:
reg.score(x,y)

0.7764803683276791

# Adj.R-Squared

In [10]:
#R^2(adj) = 1-(1-R^2)*(n-1)/(n-p-1)

In [11]:
x.shape

(100, 2)

In [12]:
r2 = reg.score(x,y)

n = x.shape[0]
p = x.shape[1]

r2_adj = 1- (1-r2)*(n-1)/(n-p-1)
r2_adj

0.7718717161282498

# Feature Selection

In [13]:
from sklearn.feature_selection import f_regression

In [14]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [15]:
p_values = f_regression(x,y)[1]
p_values

array([8.12763222e-31, 3.57340758e-01])

In [16]:
p_values.round(3)

array([0.   , 0.357])

# Summary

In [17]:
reg_summary = pd.DataFrame(['size','year'], columns= ['Features'])
reg_summary

Features
0     size
1     year

In [18]:
reg_summary['coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)
reg_summary

Features  coefficients  p-values
0     size    227.700854     0.000
1     year   2916.785327     0.357